### ISSUE TITLE
Question: Converting uuid from string type to int-array type

### ISSUE THREAD

**Issue by Quatryl23** [AjaxGb/mc-uuid-converter#2]
I need to convert the string uuid type to the int-array uuid type for my Minecraft mod but I don't know how to do it. Do you know how to convert it using Java?

**Comment by AjaxGb** [comment]
Java provides [`UUID.fromString`](https://docs.oracle.com/javase/8/docs/api/java/util/UUID.html#fromString-java.lang.String-) for converting Strings to UUIDs, and I'm sure Minecraft has a built-in function for converting UUIDs to the correct NBT representation. Googling suggests that it's something like `tag.putUuid(key, value)` where `tag` is an `NbtCompound`? If that doesn't work, just check the source code for a vanilla block or entity that stores UUIDs and see how they do it.

I recommend directing further questions to a forum dedicated to whichever modding framework you're using, as modding questions are a bit out of scope of this project. Sorry!

**Comment by Quatryl23** [comment]
Thanks
